const AUTH_URL='https://uoqastprrdlwlsesheoz.supabase.co';
const AUTH_KEY='sb_publishable_vCRrqr_Zi1Zg1N-LOrV3Q_7I0LnzKu';
const AUTH_STORE='packAuth';
const nativeFetch=window.fetch.bind(window);
function authData(){try{return JSON.parse(localStorage.getItem(AUTH_STORE)||'null')}catch{return null}}
function storeAuth(x){if(x)localStorage.setItem(AUTH_STORE,JSON.stringify(x));else localStorage.removeItem(AUTH_STORE)}
window.fetch=(input,init={})=>{let url=typeof input==='string'?input:input.url,a=authData();if(url.startsWith(AUTH_URL+'/rest/v1/')&&a?.access_token){let h=new Headers(init.headers||{});h.set('Authorization','Bearer '+a.access_token);return nativeFetch(input,{...init,headers:h})}return nativeFetch(input,init)};
async function refreshSession(){let a=authData();if(!a?.refresh_token)return false;try{let r=await nativeFetch(AUTH_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:AUTH_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:a.refresh_token})});if(!r.ok){storeAuth(null);return false}storeAuth(await r.json());return true}catch{return false}}
async function login(email,password){let r=await nativeFetch(AUTH_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:AUTH_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});let x=await r.json();if(!r.ok)throw Error(x.error_description||x.msg||'Anmeldung fehlgeschlagen');storeAuth(x);return true}
function showApp(on){document.querySelector('#loginScreen').classList.toggle('hidden',on);document.querySelector('#app').classList.toggle('hidden',!on)}
window.addEventListener('DOMContentLoaded',async()=>{let a=authData();if(a){let exp=(a.expires_at||0)*1000;if(Date.now()>exp-60000)await refreshSession();a=authData()}showApp(!!a?.access_token);if(a?.access_token&&typeof loadCloud==='function')loadCloud();let btn=document.querySelector('#loginBtn');btn.onclick=async()=>{let err=document.querySelector('#loginError');err.textContent='';btn.disabled=true;btn.textContent='Anmelden …';try{await login(document.querySelector('#loginEmail').value.trim(),document.querySelector('#loginPassword').value);document.querySelector('#loginPassword').value='';showApp(true);if(typeof loadCloud==='function')loadCloud()}catch(e){err.textContent=e.message==='Invalid login credentials'?'E-Mail oder Passwort ist falsch.':e.message}finally{btn.disabled=false;btn.textContent='Anmelden'}};document.querySelector('#loginPassword').onkeydown=e=>{if(e.key==='Enter')btn.click()};document.querySelector('#logoutBtn').onclick=async()=>{let a=authData();try{if(a?.access_token)await nativeFetch(AUTH_URL+'/auth/v1/logout',{method:'POST',headers:{apikey:AUTH_KEY,Authorization:'Bearer '+a.access_token}})}catch{}storeAuth(null);location.reload()};setInterval(refreshSession,45*60*1000)});